import pronouncing
from g2p_en import G2p
import subprocess
import re
import os

VOICE_DIR = os.environ["PIPER_VOICE_DIR"]

MODEL_PATH = os.path.join(VOICE_DIR, "en_US-lessac-medium.onnx")
CONFIG_PATH = os.path.join(VOICE_DIR, "en_US-lessac-medium.onnx.json")

def generate_audio_with_piper(text, raw_audio="raw.wav"):
    command = [
        "piper",
        "--model", MODEL_PATH,
         "--config", CONFIG_PATH,
        "--output_file", raw_audio
    ]
    process = subprocess.Popen(
        command,
        stdin=subprocess.PIPE,
        text=True
    )
    process.communicate(text)

    print(" Raw audio generated by Piper")

def build(sentence):
    
    raw_audio = "D:\\INFOSYS\\real.wav"

   # get_phonemes(sentence, phoneme_path)
    generate_audio_with_piper(sentence, raw_audio)
  
sentence = "real"
build(sentence)

